# Generated by Django 4.2.20 on 2025-07-25 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.promo'),
        ),
        migrations.AddField(
            model_name='box',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.place'),
        ),
        migrations.AddField(
            model_name='box',
            name='cell_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.boxtariff'),
        ),
    ]
