# Generated by Django 4.2.20 on 2025-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AlterField(
            model_name='clickcounter',
            name='token',
            field=models.CharField(default='X03U3RRnhVracNCi5CRk', max_length=20, unique=True),
        ),
    ]
