# Generated by Django 4.2.20 on 2025-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_order_client_alter_clickcounter_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='clickcounter',
            name='token',
            field=models.CharField(default='pKjrJQ5YFe0tJDS5HWYS', max_length=20, unique=True),
        ),
    ]
