# Generated by Django 4.2.20 on 2025-07-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_delete_client_alter_clickcounter_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Бокс', 'verbose_name_plural': 'Бокс'},
        ),
        migrations.AlterModelOptions(
            name='boxtariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тариф'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьеры'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='clickcounter',
            name='token',
            field=models.CharField(default='6X2kBbXUPL92vxiGYlCK', max_length=20, unique=True),
        ),
    ]
